/**
 * Tests for the exporters: escaping (including the hostile cases), the ledger
 * file shape, and the self-contained HTML export.
 */

import test from "node:test";
import assert from "node:assert/strict";

import { analyze } from "../app/engine/lexicon.js";
import { evaluate } from "../app/engine/engine.js";
import { appendRecord, chainDigest, documentRecord, scanRecord, verifyChain } from "../app/engine/chain.js";
import { buildStatement } from "../app/engine/statement.js";
import {
  APP_NAME, APP_VERSION, downloadName, escapeHtml, ledgerFile, reportRows, reportToMarkdown,
  safeJsonForScript, toJson, toStandaloneHtml,
} from "../app/engine/exporters.js";

const TEXT = "The voice-over in the video is synthetic speech generated by a text-to-speech model.\nPublished on our YouTube channel.";
const DECLARED = { ai_used: true, audio_output: true, video_output: true, synthetic_media: true, platform_publish: true };

async function fixture() {
  const profile = analyze(TEXT, { ...DECLARED, tools: "text-to-speech (version 2026-06)" });
  const report = evaluate({ text: TEXT, profile, packIds: ["platform-ai-labelling"], now: "2026-10-07T09:12:00.000Z" });
  let records = await appendRecord([], { ...documentRecord({ name: "note.md", digest: "a".repeat(64), chars: 10, words: 2 }), timestamp: "2026-10-07T09:12:00.000Z" });
  records = await appendRecord(records, { ...scanRecord({ report, digest: "a".repeat(64), profile }), timestamp: "2026-10-07T09:12:01.000Z" });
  const statement = buildStatement({
    profile, report, date: "2026-10-07",
    answers: { organisation: "Northlight Studio", project: "Harbour Festival", owner: "the director", reviewer: "the producer", contact: "x@example.com" },
  });
  const digest = await chainDigest(records);
  return { profile, report, statement, records, digest };
}

test("escapeHtml neutralises every dangerous character", () => {
  assert.equal(escapeHtml('<script>alert("x")</script>'), "&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;");
  assert.equal(escapeHtml("a & b 'c'"), "a &amp; b &#39;c&#39;");
  assert.equal(escapeHtml(null), "");
});

test("safeJsonForScript cannot close a script element", () => {
  const hostile = { payload: { note: "</script><img src=x onerror=alert(1)>" } };
  const json = safeJsonForScript(hostile);
  assert.ok(!json.includes("</script>"));
  assert.ok(json.includes("\\u003c/script"));
  assert.deepEqual(JSON.parse(json), hostile);
});

test("safeJsonForScript escapes line separators", () => {
  const json = safeJsonForScript("a\u2028b\u2029c");
  assert.ok(!json.includes("\u2028"));
  assert.equal(JSON.parse(json), "a\u2028b\u2029c");
});

test("ledgerFile describes itself and counts its records", async () => {
  const { records, digest } = await fixture();
  const file = ledgerFile({ records, digest, generatedAt: "2026-10-07T09:12:02.000Z", tools: { engine: "1.0.0" } });
  assert.equal(file.format, "disclosure-ledger/1");
  assert.equal(file.app, APP_NAME);
  assert.equal(file.appVersion, APP_VERSION);
  assert.equal(file.recordCount, records.length);
  assert.equal(file.engine, "1.0.0");
  assert.equal(file.digest, digest);
});

test("toJson round-trips and ends with a newline", async () => {
  const { records, digest } = await fixture();
  const text = toJson(ledgerFile({ records, digest }));
  assert.ok(text.endsWith("\n"));
  const parsed = JSON.parse(text);
  assert.equal(parsed.records.length, records.length);
});

test("exported JSON still verifies after a round trip", async () => {
  const { records, digest } = await fixture();
  const parsed = JSON.parse(toJson(ledgerFile({ records, digest })));
  const result = await verifyChain(parsed.records);
  assert.equal(result.ok, true);
});

test("reportToMarkdown covers every clause and the statement", async () => {
  const { report, statement, digest } = await fixture();
  const md = reportToMarkdown({ report, statement, digest, verification: { ok: true, checked: 2, issues: [] }, generatedAt: "2026-10-07T09:12:02.000Z" });
  assert.match(md, /# Compliance check report/);
  assert.match(md, /\*\*|Readiness: \d+\/100/);
  assert.match(md, /## Platform AI-content labelling/);
  for (const { clause } of reportRows(report)) {
    assert.ok(md.includes(clause.ref), "missing " + clause.ref);
  }
  assert.match(md, /# AI use and disclosure statement/);
});

test("reportRows walks every pack in order", async () => {
  const { report } = await fixture();
  const rows = reportRows(report);
  assert.equal(rows.length, report.summary.clauses);
  assert.equal(rows[0].pack, report.results[0].packName);
});

test("the standalone HTML carries the report, the statement and the ledger", async () => {
  const { report, statement, records, digest } = await fixture();
  const html = toStandaloneHtml({ report, statement, records, digest, generatedAt: "2026-10-07T09:12:02.000Z" });
  assert.match(html, /^<!doctype html>/);
  assert.match(html, /Clause by clause/);
  assert.match(html, /Disclosure statement draft/);
  assert.match(html, /Ledger verified|Verifying the ledger in this browser/);
  assert.ok(html.includes("P-4"));
  assert.ok(html.includes(digest));
  assert.ok(html.includes("tools/verify_ledger.py"));
  assert.ok(!html.includes("http://") || html.includes("127.0.0.1"), "the export must not pull anything off the network");
});

test("the standalone HTML escapes hostile content from the document", async () => {
  const { report } = await fixture();
  const hostile = structuredClone(report);
  hostile.results[0].clauses[0].title = "</script><script>alert(1)</script>";
  hostile.results[0].clauses[0].requirement = "\"><img src=x onerror=alert(2)>";
  const html = toStandaloneHtml({ report: hostile, records: [], digest: "d".repeat(64) });
  assert.ok(!html.includes("<script>alert(1)</script>"));
  assert.ok(html.includes("&lt;/script&gt;"));
  assert.ok(!html.includes("<img src=x"));
});

test("the standalone HTML embeds the ledger as parseable JSON", async () => {
  const { report, records, digest } = await fixture();
  const html = toStandaloneHtml({ report, records, digest });
  const match = html.match(/<script id="ledger-data" type="application\/json">([\s\S]*?)<\/script>/);
  assert.ok(match, "no ledger-data script found");
  const parsed = JSON.parse(match[1]);
  assert.equal(parsed.records.length, records.length);
  assert.equal(parsed.digest, digest);
});

test("the standalone HTML verifier re-implements the same canonical form", async () => {
  const { report, records, digest } = await fixture();
  const html = toStandaloneHtml({ report, records, digest });
  const script = html.slice(html.lastIndexOf("<script>"));
  assert.match(script, /canonical/);
  assert.match(script, /crypto\.subtle\.digest/);
  assert.match(script, /SHA-256/);
  assert.match(script, /prevHash/);
});

test("an export with no statement omits that section", async () => {
  const { report, records, digest } = await fixture();
  const html = toStandaloneHtml({ report, records, digest });
  assert.ok(!html.includes("Disclosure statement draft"));
});

test("downloadName slugs the project and keeps the date", () => {
  assert.equal(downloadName("json", { project: "Harbour Festival 2026 — asset pack", date: "2026-10-07T09:12:00.000Z" }),
    "disclosure-ledger-harbour-festival-2026-asset-pack-20261007.json");
  assert.equal(downloadName("md", {}), "disclosure-ledger-deliverable-undated.md");
});

test("app version is a semver string", () => {
  assert.match(APP_VERSION, /^\d+\.\d+\.\d+$/);
});
