/**
 * Tests for the statement builder: what it says, what it refuses to invent, and
 * what it leaves as a visible placeholder.
 */

import test from "node:test";
import assert from "node:assert/strict";

import { analyze } from "../app/engine/lexicon.js";
import { evaluate } from "../app/engine/engine.js";
import { PLACEHOLDER, buildStatement, countWords, stripMarkdown, usageSummary } from "../app/engine/statement.js";

const TEXT = [
  "Harbour Festival 2026 — delivered asset pack",
  "The voice-over in the video is synthetic speech generated by a text-to-speech model.",
  "The video and the key visuals will be published on the client's YouTube channel.",
].join("\n");

const DECLARED = {
  ai_used: true, text_output: true, visual_output: true, audio_output: true, video_output: true,
  synthetic_media: true, platform_publish: true, commercial: true,
};

function build(answers = {}, date = "2026-10-07") {
  const profile = analyze(TEXT, { ...DECLARED, tools: "text-to-speech (version 2026-06)", usageNote: "Directed by the studio." });
  const report = evaluate({ text: TEXT, profile, packIds: ["eu-ai-act-art50", "platform-ai-labelling"], now: "2026-10-07T09:12:00.000Z" });
  return buildStatement({ profile, report, answers, date });
}

const FULL_ANSWERS = {
  organisation: "Northlight Studio",
  project: "Harbour Festival 2026 — asset pack",
  owner: "the creative director",
  reviewer: "the studio producer",
  contact: "compliance@example.com",
};

test("usageSummary names the declared usage in reading order", () => {
  const profile = analyze(TEXT, DECLARED);
  const usage = usageSummary(profile);
  assert.equal(usage[0].signal, "text_output");
  assert.ok(usage.some((u) => u.signal === "audio_output"));
});

test("the statement carries the answers it was given", () => {
  const statement = build(FULL_ANSWERS);
  assert.equal(statement.organisation, "Northlight Studio");
  assert.equal(statement.project, "Harbour Festival 2026 — asset pack");
  assert.match(statement.markdown, /Northlight Studio/);
  assert.match(statement.markdown, /the studio producer reviewed and fact-checked/);
  assert.deepEqual(statement.missing, []);
});

test("missing answers become visible placeholders and are listed", () => {
  const statement = build({ organisation: "Northlight Studio" });
  assert.ok(statement.missing.includes("deliverable / project"));
  assert.ok(statement.missing.includes("reviewer"));
  assert.ok(statement.markdown.includes(PLACEHOLDER("deliverable / project")));
  assert.match(statement.markdown, /Still to fill in before this statement is sent/);
});

test("the tools line falls back to the profile when answers omit it", () => {
  const statement = build(FULL_ANSWERS);
  assert.match(statement.markdown, /text-to-speech \(version 2026-06\)/);
  assert.ok(!statement.missing.includes("tools and versions used"));
});

test("the statement lists the wording the rule packs require", () => {
  const statement = build(FULL_ANSWERS);
  assert.ok(statement.requirements.length > 0);
  assert.match(statement.markdown, /Disclosures required by the selected rule packs/);
  for (const requirement of statement.requirements) {
    assert.ok(statement.markdown.includes("[" + requirement.ref + "] " + requirement.suggestedText));
  }
});

test("the statement reports the packs and the readiness it was built from", () => {
  const statement = build(FULL_ANSWERS);
  assert.equal(statement.packs.length, 2);
  assert.match(statement.markdown, /EU AI Act — Article 50 transparency 2026\.1/);
  assert.match(statement.markdown, /Readiness:\*\* \d+\/100 \(/);
});

test("the statement says the check ran locally", () => {
  const statement = build(FULL_ANSWERS);
  assert.match(statement.markdown, /ran entirely inside the browser/);
  assert.match(statement.markdown, /no part of this deliverable was uploaded/);
});

test("the statement is deterministic for the same inputs", () => {
  assert.equal(build(FULL_ANSWERS).markdown, build(FULL_ANSWERS).markdown);
  assert.equal(build(FULL_ANSWERS).words, build(FULL_ANSWERS).words);
});

test("a different date changes the output, so the ledger digest means something", () => {
  assert.notEqual(build(FULL_ANSWERS, "2026-10-07").markdown, build(FULL_ANSWERS, "2026-10-08").markdown);
});

test("a no-AI declaration says so instead of listing empty usage", () => {
  const profile = analyze("A short note about the print run.", {});
  const report = evaluate({ text: "A short note about the print run.", profile, packIds: ["eu-ai-act-art50"] });
  const statement = buildStatement({ profile, report, answers: FULL_ANSWERS, date: "2026-10-07" });
  assert.match(statement.markdown, /No AI assistance was used in this deliverable/);
});

test("custom data-handling and rights sentences replace the defaults", () => {
  const statement = build({ ...FULL_ANSWERS, dataHandling: "We used an enterprise tenant with training disabled.", licenceNote: "All assets licensed for the client." });
  assert.match(statement.markdown, /enterprise tenant with training disabled/);
  assert.match(statement.markdown, /All assets licensed for the client/);
});

test("markdown headings are ordered and unique", () => {
  const statement = build(FULL_ANSWERS);
  const headings = statement.markdown.split("\n").filter((line) => line.startsWith("## "));
  assert.equal(headings[0], "## Statement of AI use");
  assert.equal(new Set(headings).size, headings.length);
  assert.ok(headings.includes("## Human review and responsibility"));
  assert.ok(headings.includes("## How to verify this statement"));
});

test("stripMarkdown removes heading hashes and bold markers", () => {
  const plain = stripMarkdown("# Title\n\nSome **bold** text.\n\n---\n");
  assert.ok(!plain.includes("#"));
  assert.ok(!plain.includes("**"));
  assert.match(plain, /Some bold text\./);
});

test("countWords counts words, not whitespace", () => {
  assert.equal(countWords("one two   three\nfour"), 4);
  assert.equal(countWords(""), 0);
});

test("the plain text version has no markdown left in it", () => {
  const statement = build(FULL_ANSWERS);
  assert.ok(!statement.plain.includes("#"));
  assert.ok(!statement.plain.includes("**"));
  assert.ok(statement.words > 100);
});
