/**
 * packs.js — the rule packs.
 *
 * Design rules for this file (they are part of the product's honesty claim):
 *
 *  1. No long verbatim quotations of any copyrighted or official text. Every
 *     clause is a short, hand-written paraphrase: rule name + clause number +
 *     one line of what it requires. `basis.note` says where the paraphrase comes
 *     from and that it is a paraphrase.
 *  2. Every clause declares *when it applies* (`applies`) and *what counts as
 *     satisfying it* (`satisfied`). The engine does not invent either.
 *  3. `suggestedText` is ready-to-paste wording the user can drop into the
 *     deliverable. It is a draft, not legal advice — said in the UI as well.
 *
 * Clause shape
 *   ref            clause number inside the pack, used in the gap list
 *   title          short human label
 *   requirement    one line: what the rule asks for
 *   severity       high | medium | low
 *   advisory       true -> reported as guidance, never counted as a gap
 *   applies        predicate over signals (see engine.js testPredicate)
 *   satisfied      { mode: "any" | "all", groups: [{ label, phrases: [...] }] }
 *   exemptIf       predicate; when true the clause is reported as exempt, with `exemptReason`
 *   remediation    what to do about the gap
 *   suggestedText  wording to insert into the deliverable
 *   insertInto     where in a document the wording usually belongs
 */

const AI_DISCLOSED = [
  "artificial intelligence",
  "ai-generated",
  "ai generated",
  "generated with ai",
  "generated by ai",
  "ai-assisted",
  "ai assisted",
  "with the assistance of ai",
  "using generative ai",
  "machine-generated",
  "produced with the help of an ai",
];

const TOOLS_NAMED = [
  "chatgpt",
  "gpt-4",
  "gpt-5",
  "claude",
  "gemini",
  "copilot",
  "midjourney",
  "dall-e",
  "stable diffusion",
  "flux",
  "sora",
  "runway",
  "elevenlabs",
  "whisper",
  "deepl",
  "grammarly",
  "perplexity",
  "notion ai",
];

const HUMAN_ACCOUNTABLE = [
  "reviewed by",
  "checked by",
  "verified by",
  "human review",
  "human oversight",
  "manually verified",
  "editorial responsibility",
  "approved by",
  "proofread",
  "sign-off",
  "quality assurance",
];

const PROVENANCE_MARKED = [
  "c2pa",
  "content credentials",
  "watermark",
  "invisible watermark",
  "provenance metadata",
  "machine-readable",
  "iptc",
  "signed manifest",
  "metadata records",
];

/* ------------------------------------------------------------------ *
 * Pack 1 — EU AI Act, Article 50 transparency duties (deployer view)
 * ------------------------------------------------------------------ */

const euAiAct = {
  id: "eu-ai-act-art50",
  name: "EU AI Act — Article 50 transparency",
  short: "Article 50 transparency duties for people who publish AI-assisted content.",
  jurisdiction: "European Union",
  version: "2026.1",
  updated: "2026-10-06",
  basis: {
    label: "Regulation (EU) 2024/1689 — Article 50, with Articles 4 and 113",
    note:
      "Hand-written paraphrase of the transparency duties, one line per obligation. " +
      "Not a quotation of the Regulation, not legal advice. Article 113 sets 2 August 2026 " +
      "as the application date of the Article 50 duties; confirm the current date and your role " +
      "(provider or deployer) before relying on this pack.",
  },
  clauses: [
    {
      ref: "Art. 50(1)",
      title: "Tell people they are dealing with an AI system",
      requirement:
        "An AI system that interacts directly with people must make clear that it is an AI system, at the latest at the first interaction.",
      severity: "high",
      applies: { any: ["interactive"] },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "an explicit AI-identity notice",
            phrases: [
              "you are interacting with an artificial intelligence",
              "you are interacting with an ai",
              "you are talking to an ai",
              "this chat is automated",
              "you are chatting with an ai",
              "this is an automated assistant",
              "this conversation is handled by an ai",
            ],
          },
        ],
      },
      remediation:
        "Put a one-line notice where the conversation starts, before the first message is sent, and keep it visible in the transcript.",
      suggestedText:
        "You are interacting with an artificial intelligence system, not a human colleague. " +
        "A named member of our team reviews the output before it is used.",
      insertInto: "first screen of the chat or assistant, before the user's first message",
    },
    {
      ref: "Art. 50(2)",
      title: "Mark synthetic output in a machine-readable way",
      requirement:
        "Providers of generative systems must mark synthetic audio, image, video and text output so that it is detectable as artificially generated.",
      severity: "high",
      applies: { any: ["visual_output", "audio_output", "video_output", "synthetic_media"] },
      satisfied: {
        mode: "any",
        groups: [
          { label: "a provenance or watermarking commitment", phrases: PROVENANCE_MARKED },
        ],
      },
      remediation:
        "Attach Content Credentials (C2PA) or an equivalent signed manifest to delivered files, " +
        "and state in the hand-over note which files carry them.",
      suggestedText:
        "Delivered files carry Content Credentials (C2PA) provenance metadata and an invisible watermark. " +
        "The manifest records the tool, the date and the prompt identifier for every generated asset.",
      insertInto: "asset register or file hand-over notes",
    },
    {
      ref: "Art. 50(4)(a)",
      title: "Disclose AI text published on matters of public interest",
      requirement:
        "Where generative AI produces text that is published to inform the public on matters of public interest, the publication must disclose that the content was generated or manipulated by AI.",
      severity: "high",
      applies: { all: [{ signal: "ai_used" }, { signal: "public_interest" }] },
      exemptIf: { all: [{ signal: "human_review" }, { signal: "public_interest" }] },
      exemptReason:
        "Article 50(6): the duty does not apply to AI-generated content that has undergone human review or " +
        "editorial control where a named person or organisation holds editorial responsibility for publication.",
      satisfied: {
        mode: "any",
        groups: [{ label: "a published AI-origin disclosure", phrases: AI_DISCLOSED }],
      },
      remediation:
        "Add a standing disclosure line to the publication itself — visible in the article, not only in an internal note — and keep the editorial responsibility statement with it.",
      suggestedText:
        "This article was drafted with the assistance of artificial intelligence and edited, " +
        "checked and approved by a named editor who is responsible for its content.",
      insertInto: "footer of the published article, and the publication's standing AI policy page",
    },
    {
      ref: "Art. 50(4)(b)",
      title: "Disclose deep fakes",
      requirement:
        "A person who creates or manipulates image, audio or video content that looks like real people, places or events must disclose that the content is artificially generated or manipulated.",
      severity: "high",
      applies: { any: ["synthetic_media", "visual_output", "audio_output", "video_output"] },
      satisfied: {
        mode: "any",
        groups: [{ label: "a synthetic-media disclosure", phrases: AI_DISCLOSED }],
      },
      remediation:
        "Label the artefact itself, not just the accompanying document: a human-perceptible label on the image, video or audio. For evidently artistic, satirical or fictional work the disclosure may be made in a way that does not spoil the work — but it must still exist.",
      suggestedText:
        "The images and audio in this deliverable are synthetic: they were generated or edited with artificial " +
        "intelligence and do not depict real events. A visible label is carried on each synthetic asset.",
      insertInto: "on the asset itself, plus a disclosure note in the presentation annex",
    },
    {
      ref: "Art. 50(3)",
      title: "Inform people exposed to emotion or biometric systems",
      requirement:
        "Deployers of emotion recognition or biometric categorisation systems must inform the people exposed to them, and process personal data lawfully.",
      severity: "medium",
      applies: { any: ["biometric"] },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "an information notice for biometric or emotion analysis",
            phrases: [
              "emotion recognition",
              "biometric categorisation",
              "biometric categorization",
              "we analyse facial",
              "sentiment analysis is carried out",
              "information notice",
              "persons exposed",
            ],
          },
        ],
      },
      remediation:
        "Publish the notice where the system is used, name the purpose and the categories of data, and keep the record of who was informed.",
      suggestedText:
        "This system performs emotion recognition. The people exposed to it are informed before capture, " +
        "the purpose is limited to quality assurance, and no biometric categorisation is performed.",
      insertInto: "privacy notice and any on-site signage next to the capture point",
    },
    {
      ref: "Art. 50(5)",
      title: "Make the disclosure clear, distinguishable and timely",
      requirement:
        "The disclosure must be clear, distinguishable, given at the latest at the time of the first interaction or exposure, accessible, and human-perceptible for deep-fake disclosures.",
      severity: "medium",
      applies: { signal: "ai_used" },
      satisfied: {
        mode: "all",
        groups: [
          { label: "a located disclosure", phrases: AI_DISCLOSED },
          {
            label: "a statement of when it is given",
            phrases: [
              "at the point of first",
              "before first use",
              "at the start of",
              "given at the latest",
              "at the top of this document",
              "at first exposure",
            ],
          },
        ],
      },
      remediation:
        "Move the disclosure to the first place a reader or viewer looks, keep it visually distinguishable from the surrounding copy, and say when it is given.",
      suggestedText:
        "Disclosure: parts of this deliverable were produced with artificial intelligence. " +
        "This notice is given at the start of the deliverable, at first exposure, and is repeated in the hand-over note.",
      insertInto: "top of the deliverable, above the first heading",
    },
    {
      ref: "Art. 50(6)",
      title: "Record who carries editorial responsibility",
      requirement:
        "The carve-out for reviewed content only works if a named person or organisation holds editorial responsibility — so the record of that responsibility has to exist.",
      severity: "low",
      advisory: true,
      applies: { any: ["public_interest", "platform_publish"] },
      satisfied: {
        mode: "any",
        groups: [{ label: "a named editorial responsibility", phrases: HUMAN_ACCOUNTABLE }],
      },
      remediation:
        "Name the person who carries editorial responsibility for published AI-assisted content, and keep the review record with the publication.",
      suggestedText:
        "Editorial responsibility for this publication is held by the named editor listed in the imprint; " +
        "the AI-assisted draft was reviewed against the editorial policy before publication.",
      insertInto: "imprint or publishing policy page",
    },
    {
      ref: "Art. 4",
      title: "AI literacy of the people using the tools",
      requirement:
        "People who work with AI systems on an organisation's behalf should have a sufficient level of AI literacy for their role.",
      severity: "low",
      advisory: true,
      applies: { signal: "ai_used" },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "a training or policy statement",
            phrases: ["ai literacy", "ai training", "internal ai policy", "use guidelines", "staff training", "competence"],
          },
        ],
      },
      remediation:
        "Record who has been trained, what the internal AI use policy says, and when it was last reviewed.",
      suggestedText:
        "Everyone using generative tools on this project has completed the internal AI literacy briefing, " +
        "and works to the AI use policy reviewed in 2026.",
      insertInto: "method statement or quality section",
    },
  ],
};

/* ------------------------------------------------------------------ *
 * Pack 2 — public-sector tender / bid AI-use declaration
 * ------------------------------------------------------------------ */

const tenderAiDisclosure = {
  id: "tender-ai-declaration",
  name: "Tender AI-use declaration",
  short: "The AI disclosure clauses public buyers now ask bidders to sign.",
  jurisdiction: "Public procurement (EU/UK-style ITTs)",
  version: "2026.1",
  updated: "2026-10-06",
  basis: {
    label: "Compiled from AI-use declaration clauses seen in public-sector ITTs",
    note:
      "These clauses are a hand-written consolidation of requirements that appear in invitation-to-tender " +
      "AI-use declarations. Individual buyers word them differently and number them differently — " +
      "always read the ITT itself. Clause references here are this pack's own numbering.",
  },
  clauses: [
    {
      ref: "T-1",
      title: "Declare whether AI was used at all",
      requirement:
        "State plainly whether generative AI was used in preparing the submission, including a negative declaration when it was not.",
      severity: "high",
      applies: { signal: "tender" },
      satisfied: {
        mode: "any",
        groups: [
          { label: "a positive declaration", phrases: AI_DISCLOSED },
          {
            label: "a negative declaration",
            phrases: [
              "no artificial intelligence",
              "no ai was used",
              "no generative ai",
              "not used any ai",
              "without the use of ai",
              "no ai tools were used",
            ],
          },
        ],
      },
      remediation:
        "Add an AI use declaration as its own headed section, and say explicitly that no AI was used if that is the case — silence reads as a missing declaration.",
      suggestedText:
        "AI use declaration: generative artificial intelligence was used in preparing this submission " +
        "in the ways set out in T-3 below. No other AI systems were used.",
      insertInto: "a dedicated 'AI use declaration' section, page 2 of the submission",
    },
    {
      ref: "T-2",
      title: "Name the tools and models",
      requirement:
        "List the AI tools and model versions used, so the buyer can assess the risk and reproducibility of the submission.",
      severity: "high",
      applies: { signal: "tender" },
      satisfied: {
        mode: "any",
        groups: [{ label: "named tools", phrases: TOOLS_NAMED }],
      },
      remediation:
        "Give a short table: tool name, model version, date of use, purpose. Avoid 'an AI tool' — name it.",
      suggestedText:
        "Tools used: ChatGPT (model version recorded in Annex A), Claude (model version recorded in Annex A). " +
        "Only these tools were used, and only on the sections listed in the extent statement.",
      insertInto: "Annex A — tool and version register",
    },
    {
      ref: "T-3",
      title: "State the extent: which sections were AI-assisted",
      requirement:
        "Identify which parts of the submission were produced with AI assistance, so that authorship and responsibility are clear.",
      severity: "high",
      applies: { signal: "tender" },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "a section-level extent statement",
            phrases: [
              "sections listed",
              "sections below",
              "ai-assisted sections",
              "the following sections",
              "extent of ai",
              "limited to the following",
              "no ai was used in the technical",
            ],
          },
        ],
      },
      remediation:
        "List the affected sections by heading or page number. A general statement without sections will not survive evaluation.",
      suggestedText:
        "Extent: AI assistance was limited to the following sections — Executive summary (2.1), Market analysis (4.3), " +
        "and the covering letter. The technical solution, pricing and staffing chapters were written without AI.",
      insertInto: "same AI use declaration section, immediately after T-1",
    },
    {
      ref: "T-4",
      title: "Name the human who verified the content",
      requirement:
        "Confirm that a named, accountable person has checked the AI-assisted content for accuracy and takes responsibility for the submission.",
      severity: "high",
      applies: { signal: "tender" },
      satisfied: {
        mode: "all",
        groups: [
          { label: "a review statement", phrases: HUMAN_ACCOUNTABLE },
          {
            label: "a named or role-identified person",
            phrases: ["on behalf of", "authorised signatory", "authorized signatory", "bid manager", "director", "named above", "signed by"],
          },
        ],
      },
      remediation:
        "Add the reviewer's name or role plus the date, and make sure it matches the person who signs the bid.",
      suggestedText:
        "Every AI-assisted section was reviewed and fact-checked by the bid manager named in the form of tender. " +
        "The AI-assisted content does not include any factual claim we cannot support with the evidence in Annex B.",
      insertInto: "AI use declaration section, plus the form of tender signature block",
    },
    {
      ref: "T-5",
      title: "Confirm no confidential material went into a public AI service",
      requirement:
        "Confirm that tender-restricted, personal or confidential information was not submitted to third-party AI services, and say what was done instead.",
      severity: "high",
      applies: { signal: "tender" },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "a data-handling statement",
            phrases: [
              "no confidential information",
              "no personal data was",
              "not submitted to any third-party ai",
              "no client data",
              "confidential material was not",
              "under the terms of use",
              "data processing agreement",
              "no personal data entered",
              "no tender-restricted, confidential or personal data",
              "confidential or personal data was not",
            ],
          },
        ],
      },
      remediation:
        "State the rule plainly, name the safeguards (enterprise tenant, training opt-out, data processing agreement), and confirm who enforces it.",
      suggestedText:
        "No tender-restricted, confidential or personal data was entered into any third-party AI service. " +
        "Prompts were limited to public-domain material and our own non-confidential drafts.",
      insertInto: "AI use declaration section, and the information security questionnaire if one is issued",
    },
    {
      ref: "T-6",
      title: "Confirm authorship and third-party rights",
      requirement:
        "Confirm the submission is the bidder's own work, that AI output was not copied from another source, and that no third-party rights are infringed.",
      severity: "medium",
      applies: { signal: "tender" },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "an originality statement",
            phrases: [
              "our own work",
              "original work",
              "does not infringe",
              "third-party rights",
              "third party rights",
              "all rights cleared",
              "no third-party material",
              "copyright clearance",
            ],
          },
        ],
      },
      remediation:
        "Add the originality paragraph, and keep the plagiarism check record for any AI-assisted text chapter.",
      suggestedText:
        "This submission is our own work. AI-generated text was checked for originality before use, and no " +
        "third-party material is included without a cleared licence.",
      insertInto: "declarations section, next to the existing non-collusion declaration",
    },
    {
      ref: "T-7",
      title: "Keep the record for the retention period",
      requirement:
        "Keep an auditable record of AI use (tool, version, date, purpose) and be able to produce it on request during the procurement and the contract term.",
      severity: "medium",
      applies: { all: [{ signal: "tender" }, { signal: "ai_used" }] },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "a retention commitment",
            phrases: [
              "retained for",
              "retention period",
              "available on request",
              "produced on request",
              "audit trail",
              "kept for the duration",
              "we can provide on request",
            ],
          },
        ],
      },
      remediation:
        "Keep the tool register and the hash-chained record with the bid file, and say for how long.",
      suggestedText:
        "The AI use record for this bid — tool, model version, date of use, sections affected — is retained with the " +
        "bid file for the contract retention period and can be produced on request.",
      insertInto: "AI use declaration section, closing sentence",
    },
    {
      ref: "T-8",
      title: "Flag any AI-assisted pricing or cost model",
      requirement:
        "Where AI assisted commercial content — pricing, cost models, programme dates — flag it, because those figures carry contractual weight.",
      severity: "low",
      applies: { any: ["tender", "commercial"] },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "a commercial-content statement",
            phrases: [
              "pricing was not prepared",
              "no ai was used in the pricing",
              "the pricing model was prepared",
              "commercial figures were checked",
              "prices were calculated",
              "checked arithmetically",
            ],
          },
        ],
      },
      remediation:
        "Either state that commercial figures were prepared without AI, or state who re-checked them by hand.",
      suggestedText:
        "The pricing schedule was prepared without AI assistance and every figure was checked arithmetically " +
        "by the commercial manager before submission.",
      insertInto: "pricing schedule cover note",
    },
  ],
};

/* ------------------------------------------------------------------ *
 * Pack 3 — platform AI content labelling
 * ------------------------------------------------------------------ */

const platformLabelling = {
  id: "platform-ai-labelling",
  name: "Platform AI-content labelling",
  short: "Labelling and provenance duties before you upload to a content platform.",
  jurisdiction: "Content platforms (common requirement set)",
  version: "2026.1",
  updated: "2026-10-06",
  basis: {
    label: "Compiled from the published AI-disclosure rules of major platforms",
    note:
      "Each major platform states its own labelling rule and changes it without notice (upload-flow " +
      "'altered or synthetic content' questions, 'AI info' labels, C2PA support, synthetic-voice rules). " +
      "This pack is our consolidation of the requirements they have in common, written from scratch; " +
      "it is not a quotation of any platform's policy. Check the current policy of the platform you publish to.",
  },
  clauses: [
    {
      ref: "P-1",
      title: "Ask for the disclosure before you publish",
      requirement:
        "Realistic altered or synthetic content must be disclosed when it is uploaded, not added afterwards.",
      severity: "high",
      applies: { any: ["platform_publish", "synthetic_media"] },
      satisfied: {
        mode: "any",
        groups: [{ label: "an AI-origin disclosure", phrases: AI_DISCLOSED }],
      },
      remediation:
        "Tick the platform's synthetic-content question at upload time and keep the answer recorded with the asset.",
      suggestedText:
        "Synthetic or altered content disclosure: this video contains AI-generated visuals and synthetic narration; " +
        "the disclosure was declared at upload.",
      insertInto: "asset log and the platform's upload declaration",
    },
    {
      ref: "P-2",
      title: "Put the label in the caption when the tool has no label field",
      requirement:
        "If the platform has no structured disclosure field, the label must appear in the description or caption where the audience sees it.",
      severity: "high",
      applies: { signal: "platform_publish" },
      satisfied: {
        mode: "any",
        groups: [{ label: "a caption disclosure", phrases: AI_DISCLOSED }],
      },
      remediation: "Put the first line of the caption to work: name the AI content before the hashtags.",
      suggestedText:
        "Contains AI-generated visuals and synthetic voice. Every claim in this video was checked against " +
        "the source documents linked below.",
      insertInto: "first line of the caption or description",
    },
    {
      ref: "P-3",
      title: "Attach provenance metadata where the format allows it",
      requirement:
        "Carry machine-readable provenance (for example C2PA/Content Credentials or an equivalent manifest) into the exported file so labels survive re-encoding.",
      severity: "medium",
      applies: { any: ["visual_output", "audio_output", "video_output"] },
      satisfied: {
        mode: "any",
        groups: [{ label: "a provenance marker", phrases: PROVENANCE_MARKED }],
      },
      remediation:
        "Export with the provenance manifest attached, keep the original file as the master, and record the " +
        "asset digest so you can show the published file matches the master.",
      suggestedText:
        "The published file carries a Content Credentials manifest; the master file digest is recorded in the " +
        "asset log so the published copy can be matched to it.",
      insertInto: "asset log, alongside the file digest",
    },
    {
      ref: "P-4",
      title: "Disclose synthetic voice and audio even when the picture is real",
      requirement:
        "Cloned or synthesised speech must be disclosed separately from the visual content.",
      severity: "high",
      applies: { any: ["audio_output", "synthetic_media"] },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "a voice disclosure",
            phrases: [
              "synthetic voice",
              "voice was generated",
              "ai voice",
              "cloned voice",
              "synthesised speech",
              "synthesized speech",
              "narrated by an ai",
              "text-to-speech",
            ],
          },
        ],
      },
      remediation:
        "Name the voice in the disclosure: which system, whether a real person's voice was cloned, and whether consent was obtained.",
      suggestedText:
        "The narration is synthetic speech generated by a text-to-speech system. It is not a recording of a " +
        "real person's voice, and no voice was cloned.",
      insertInto: "caption disclosure and the video's end card",
    },
    {
      ref: "P-5",
      title: "Do not strip an existing AI label",
      requirement:
        "An AI label or provenance manifest already attached to source material must not be removed, obscured or cropped away.",
      severity: "medium",
      applies: { signal: "platform_publish" },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "a no-stripping commitment",
            phrases: [
              "labels are preserved",
              "we do not remove labels",
              "are preserved in the published version",
              "provenance is preserved",
              "credits are retained",
              "manifest retained",
              "not stripped",
            ],
          },
        ],
      },
      remediation:
        "Add the commitment to your publishing checklist, and keep the source manifests with the master file.",
      suggestedText:
        "Existing AI labels and provenance manifests in source material are preserved in the published version; " +
        "our publishing checklist requires the manifest to be verified after export.",
      insertInto: "publishing checklist / editorial policy",
    },
    {
      ref: "P-6",
      title: "Keep the disclosure when the asset is reused",
      requirement:
        "When AI-created content is re-cut, re-uploaded or repurposed, the original disclosure travels with it.",
      severity: "medium",
      applies: { any: ["platform_publish", "commercial"] },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "a reuse rule",
            phrases: [
              "carried forward",
              "travels with",
              "reused with the disclosure",
              "re-upload",
              "repurposed",
              "the label is repeated",
              "same disclosure",
            ],
          },
        ],
      },
      remediation: "Write the rule into the asset log so a re-cut cannot silently lose the label.",
      suggestedText:
        "This disclosure travels with the asset: any re-cut, re-upload or client reuse carries the same " +
        "AI-origin statement and manifest.",
      insertInto: "asset log entry, licensing terms for the client",
    },
    {
      ref: "P-7",
      title: "Disclose AI content in paid promotion",
      requirement:
        "AI-generated realistic content used in advertising or paid promotion must be disclosed, over and above the ordinary ad label.",
      severity: "medium",
      applies: { any: ["commercial", "platform_publish"] },
      satisfied: {
        mode: "any",
        groups: [{ label: "an advertising disclosure", phrases: AI_DISCLOSED }],
      },
      remediation:
        "Add the AI line to the ad copy and to the paid-promotion disclosure field, and keep it in the client approval record.",
      suggestedText:
        "This promoted content uses AI-generated imagery; the AI-origin disclosure is included in the ad copy " +
        "and in the paid-promotion declaration.",
      insertInto: "ad copy and paid-promotion declaration",
    },
    {
      ref: "P-8",
      title: "Decide, and record, whether the content is clearly unrealistic",
      requirement:
        "Where a platform exempts obviously unrealistic content, the decision to rely on that exemption has to be recorded and defensible.",
      severity: "low",
      advisory: true,
      applies: { any: ["visual_output", "video_output"] },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "a stylistic exemption note",
            phrases: [
              "clearly unrealistic",
              "obviously animated",
              "stylised animation",
              "stylized animation",
              "cartoon",
              "not photorealistic",
              "not photo-realistic",
            ],
          },
        ],
      },
      remediation:
        "Note the reason in the asset log. Anything photorealistic should simply be labelled rather than argued about.",
      suggestedText:
        "The animated segments are stylised and clearly unrealistic, so no realism label is claimed for them; " +
        "the photorealistic segments are labelled individually.",
      insertInto: "asset log — exemption note",
    },
  ],
};

/* ------------------------------------------------------------------ *
 * Pack 4 — design / creative competition AI declaration
 * ------------------------------------------------------------------ */

const competitionDeclaration = {
  id: "competition-ai-declaration",
  name: "Competition AI declaration",
  short: "The AI declaration design and creative competitions ask entrants for.",
  jurisdiction: "Design and creative competitions (generic template)",
  version: "2026.1",
  updated: "2026-10-06",
  basis: {
    label: "Generic template drawn from competition entry rules that require an AI declaration",
    note:
      "Competitions differ: some ban generative AI for final artwork, some allow it with a declaration, some " +
      "require a per-image statement. This pack states the declaration a jury normally asks for. " +
      "It is a template written by us, not the rules of any specific competition — read your own brief first.",
  },
  clauses: [
    {
      ref: "D-1",
      title: "Declare AI use, or declare that there was none",
      requirement:
        "State whether AI was used in producing the entry. A blank is treated as an incomplete declaration.",
      severity: "high",
      applies: { signal: "competition" },
      satisfied: {
        mode: "any",
        groups: [
          { label: "a positive declaration", phrases: AI_DISCLOSED },
          {
            label: "a negative declaration",
            phrases: [
              "no ai was used",
              "no artificial intelligence",
              "without the use of ai",
              "no generative ai",
              "nothing was generated by ai",
            ],
          },
        ],
      },
      remediation: "One short paragraph, signed and dated, in the entry document or the form's declaration field.",
      suggestedText:
        "AI declaration: I used generative artificial intelligence for the tasks listed below, and I declare that " +
        "the concept, the design decisions and the final selection of work are my own.",
      insertInto: "entry document, directly under the project title",
    },
    {
      ref: "D-2",
      title: "Say what kind of use it was",
      requirement:
        "Describe the type of AI use: ideation, drafting, image generation, retouching, translation, code, or none.",
      severity: "high",
      applies: { any: ["competition", "ai_used"] },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "a use-type statement",
            phrases: [
              "ideation",
              "brainstorming",
              "image generation",
              "generated images",
              "retouching",
              "upscaling",
              "translation",
              "translated",
              "moodboard",
              "mood board",
              "concept development",
              "drafting",
            ],
          },
        ],
      },
      remediation: "Use the competition's own vocabulary for the tasks, and be specific about images versus text.",
      suggestedText:
        "Type of use: brainstorming and moodboard exploration; text drafting for the description; upscaling of " +
        "my own photographs and diagrams.",
      insertInto: "AI declaration paragraph, second sentence",
    },
    {
      ref: "D-3",
      title: "Identify which delivered assets are AI-generated",
      requirement:
        "Name the submitted assets that were generated or substantially modified with AI, file by file.",
      severity: "high",
      applies: { any: ["competition", "visual_output"] },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "an asset-level list",
            phrases: [
              "as follows",
              "listed below",
              "the following assets",
              "file ",
              "image 1",
              "figure 1",
              "asset list",
              "assets:",
              "all other submitted assets",
              "no submitted asset",
            ],
          },
        ],
      },
      remediation:
        "Give a table: file name, generated or hand-made, tool, date. Juries check this against the filenames.",
      suggestedText:
        "Assets: 01_hero.jpg and 03_poster.jpg were generated with an image model and then edited by hand; " +
        "all other submitted assets were made without AI.",
      insertInto: "asset table in the entry document",
    },
    {
      ref: "D-4",
      title: "Confirm the rights position of AI-assisted assets",
      requirement:
        "Confirm you hold the rights you are granting, and that AI-assisted assets do not infringe third-party rights.",
      severity: "medium",
      applies: { any: ["competition", "ai_used"] },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "a rights statement",
            phrases: [
              "i hold the rights",
              "we hold the rights",
              "does not infringe",
              "no third-party rights",
              "rights are cleared",
              "licence",
              "license",
              "model terms permit",
              "non-infringing",
            ],
          },
        ],
      },
      remediation:
        "Check the terms of the model you used — several forbid commercial use or claim rights in the output — and record the terms version.",
      suggestedText:
        "I hold the rights I am granting. The AI-assisted assets were produced with tools whose terms permit " +
        "commercial use, and they do not reproduce a recognisable third-party work.",
      insertInto: "AI declaration paragraph, closing sentence",
    },
    {
      ref: "D-5",
      title: "State that a human made the creative decisions",
      requirement:
        "Confirm human authorship of the concept, the design decisions and the final selection of submitted work.",
      severity: "high",
      applies: { signal: "competition" },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "a human-authorship statement",
            phrases: [
              "my own",
              "made by me",
              "were made by",
              "human authorship",
              "i made the design decisions",
              "the design decisions are mine",
              "final selection",
              "no content was generated without my review",
              "directed by me",
              "my own hand",
            ],
          },
        ],
      },
      remediation:
        "Describe the loop: what the AI proposed, what you changed, why. Juries reward a checkable process.",
      suggestedText:
        "The concept, composition and final selection are mine. Where a model produced a candidate image, " +
        "I changed the composition and colour and re-rendered the final artwork by hand.",
      insertInto: "process or method statement",
    },
    {
      ref: "D-6",
      title: "Meet the declaration's form and length limit",
      requirement:
        "Declarations often carry a word limit and a required location; an over-long or misplaced declaration is treated as a missing one.",
      severity: "medium",
      applies: { signal: "competition" },
      satisfied: {
        mode: "all",
        groups: [
          { label: "a declaring heading or field", phrases: ["ai declaration", "ai use declaration", "declaration of ai", "ai statement"] },
          { label: "a length-managed paragraph", phrases: ["words", "characters", "as required by the brief", "within the limit"] },
        ],
      },
      remediation:
        "Put the declaration where the brief asks for it, keep it inside the stated word count, and check the count.",
      suggestedText:
        "AI declaration (142 words, within the brief's 150-word limit) — provided in the entry document and " +
        "repeated in the form's declaration field, as the brief requires.",
      insertInto: "wherever the brief says the declaration belongs; repeat it in the form field",
    },
    {
      ref: "D-7",
      title: "Record tool names, versions and dates",
      requirement:
        "Keep a record of which tools and model versions were used, and when, so the declaration can be verified later.",
      severity: "medium",
      applies: { any: ["competition", "ai_used"] },
      satisfied: {
        mode: "any",
        groups: [{ label: "tool and version record", phrases: TOOLS_NAMED.concat(["version recorded in the appendix", "dated in the appendix", "listed in the appendix"]) }],
      },
      remediation: "A small table is enough: tool, version, date, task. Keep the prompts or seeds with it.",
      suggestedText:
        "Tools: image model (version recorded in the appendix), text assistant (version recorded in the appendix). " +
        "Every use is dated in the appendix.",
      insertInto: "appendix to the entry document",
    },
    {
      ref: "D-8",
      title: "Do not depict real people without consent",
      requirement:
        "AI-generated likenesses of identifiable people need consent; competitions disqualify entries that use them without it.",
      severity: "low",
      advisory: true,
      applies: { any: ["visual_output", "audio_output"] },
      satisfied: {
        mode: "any",
        groups: [
          {
            label: "a likeness-consent statement",
            phrases: [
              "with consent",
              "no identifiable person",
              "consent was obtained",
              "release form",
              "not a real person",
              "does not depict a real person",
              "no submitted asset depicts",
              "fictional person",
            ],
          },
        ],
      },
      remediation: "Either route: consent form on file, or state that no generated asset depicts an identifiable person.",
      suggestedText:
        "No submitted asset depicts an identifiable real person or a real person's voice; all figures shown are fictional.",
      insertInto: "AI declaration paragraph or its own short annex",
    },
  ],
};

export const PACKS = [euAiAct, tenderAiDisclosure, platformLabelling, competitionDeclaration];

export const PACK_INDEX = Object.fromEntries(PACKS.map((p) => [p.id, p]));

/** Total clause count across all packs — used by the UI and by tests. */
export const TOTAL_CLAUSES = PACKS.reduce((n, p) => n + p.clauses.length, 0);

export function getPack(id) {
  const pack = PACK_INDEX[id];
  if (!pack) throw new Error("unknown rule pack: " + id);
  return pack;
}

export function clauseById(packId, ref) {
  const pack = getPack(packId);
  const clause = pack.clauses.find((c) => c.ref === ref);
  if (!clause) throw new Error("unknown clause: " + packId + " " + ref);
  return clause;
}
