/**
 * samples.js — four short, realistic documents used for the guided tour, the
 * screenshots and the tests. They are written for this project; none of them is
 * a real client document.
 *
 * Each sample carries the usage declaration a real user would tick, the packs
 * that fit it, and the statement fields — so the tour exercises the whole
 * pipeline with real input instead of a canned result.
 */

export const SAMPLES = [
  {
    id: "agency-deliverable",
    label: "Agency deliverable note (images, video, platform)",
    filename: "harbour-festival-deliverable-note.md",
    declared: {
      ai_used: true,
      generative_output: true,
      text_output: true,
      visual_output: true,
      video_output: true,
      audio_output: true,
      synthetic_media: true,
      platform_publish: true,
      commercial: true,
      rights: true,
    },
    tools: "Image model (version 2026-08), video model (version 2026-07), text assistant (version 2026-09), text-to-speech (version 2026-06)",
    usageNote:
      "The art direction, the storyboard and the final selection were made by the studio. The model produced candidate frames from our own sketches.",
    packs: ["eu-ai-act-art50", "platform-ai-labelling"],
    answers: {
      organisation: "Northlight Studio",
      project: "Harbour Festival 2026 campaign — delivered asset pack",
      owner: "the creative director",
      reviewer: "the studio producer",
      dataHandling:
        "No client-confidential or personal data was entered into any third-party AI service; the studio tenant accounts are set to opt out of training.",
    },
    text: [
      "Harbour Festival 2026 — delivered asset pack",
      "",
      "This note accompanies the campaign assets delivered to the client on 6 October 2026.",
      "It records how the assets were made, what was generated, and what the client needs to do before publication.",
      "",
      "1. What was made",
      "The pack contains a 45-second video, six key visuals for print and social media, and the copy for the landing page.",
      "The concept, the composition of every hero frame and the final selection were directed by the studio.",
      "Candidate frames were produced with an image model from our own sketches, then re-composed by hand.",
      "The voice-over in the video is synthetic speech generated by a text-to-speech model.",
      "",
      "2. Where the assets will be published",
      "The video and the key visuals will be published on the client's YouTube channel and on Instagram, and used in paid promotion.",
      "",
      "3. Before publication",
      "The client signs off the final cut. The studio will hand over the working files and the asset log on request.",
      "",
    ].join("\n"),
  },
  {
    id: "tender-response",
    label: "Public tender response (AI use declaration)",
    filename: "itt-2026-044-ai-use-declaration.md",
    declared: {
      ai_used: true,
      generative_output: true,
      text_output: true,
      tender: true,
      commercial: true,
      human_review: true,
      rights: true,
    },
    tools: "Text assistant (version 2026-05) for drafting; no image tools",
    usageNote: "Drafts were produced from our own source material and the authority's public documents.",
    packs: ["tender-ai-declaration", "eu-ai-act-art50"],
    answers: {
      organisation: "Meridian Consulting",
      project: "ITT 2026-044 — service transformation bid",
      owner: "the bid director",
      reviewer: "the bid manager named in the form of tender",
      contact: "compliance@example.com",
      dataHandling:
        "No personal data was entered into any third-party AI service, and no client data left our tenant; the assistant was used under an enterprise agreement with training disabled.",
    },
    text: [
      "ITT 2026-044 — AI use declaration",
      "",
      "We confirm that generative artificial intelligence was used in preparing this submission, as set out below.",
      "",
      "Tools used: a text assistant (version 2026-05) running in our enterprise tenant. No other AI tools were used.",
      "",
      "Human review: every AI-assisted paragraph was reviewed by the bid manager, who checked each factual claim against the source documents in Annex B.",
      "",
      "Confidentiality: no personal data was entered into any third-party AI service. No client data, and no material marked restricted by the contracting authority, was placed in a prompt.",
      "",
      "Authorship: this submission is our own work and it does not infringe any third-party rights. AI-generated text was checked for originality before use.",
      "",
      "Pricing: prices were calculated and checked arithmetically by the commercial manager without AI assistance.",
      "",
      "Signed on behalf of Meridian Consulting, 6 October 2026.",
      "",
    ].join("\n"),
  },
  {
    id: "newsroom-note",
    label: "Newsroom article (editorial control stated)",
    filename: "public-interest-article-notes.md",
    declared: {
      ai_used: true,
      generative_output: true,
      text_output: true,
      public_interest: true,
      human_review: true,
      platform_publish: true,
    },
    tools: "Text assistant (version 2026-04)",
    usageNote: "The assistant produced a first draft from the reporter's notes; the reporter rewrote the opening and verified every figure.",
    packs: ["eu-ai-act-art50"],
    answers: {
      organisation: "Civic Record Desk",
      project: "Feature: the harbour redevelopment consultation",
      owner: "the editor",
      reviewer: "the duty editor",
      contact: "editors@example.com",
    },
    text: [
      "Feature: the harbour redevelopment consultation",
      "",
      "Editorial note: this article was drafted with the assistance of a text assistant and then rewritten by the reporter.",
      "Human review: the duty editor has editorial responsibility for the published text and signed it off before publication.",
      "Every figure was checked against the consultation documents published by the municipal authority.",
      "",
      "The article itself runs to 1,400 words on the public consultation page of the newspaper's website.",
      "",
    ].join("\n"),
  },
  {
    id: "competition-entry",
    label: "Design competition entry (AI declaration)",
    filename: "open-call-entry-ai-declaration.md",
    declared: {
      ai_used: true,
      generative_output: true,
      text_output: true,
      visual_output: true,
      competition: true,
      translation: false,
    },
    tools: "Image model (version 2026-03) for moodboard exploration only",
    usageNote: "The final artwork is hand-drawn; the model was used to explore lighting directions.",
    packs: ["competition-ai-declaration"],
    answers: {
      organisation: "Studio Kusaki",
      project: "Open Call 2026 — 'Waterline' entry",
      owner: "the designer",
      reviewer: "the designer",
      contact: "studio@example.com",
    },
    text: [
      "Open Call 2026 — entry document",
      "",
      "AI declaration: generative artificial intelligence was used for brainstorming and moodboard exploration at the start of the project.",
      "The concept, the composition and the final artwork were made by me and not by a model.",
      "The images in the moodboard were generated with an image model; the submitted final artwork is hand-drawn and carries no generated pixels.",
      "I hold the rights I am granting and the AI-assisted material does not reproduce a recognisable third-party work.",
      "",
    ].join("\n"),
  },
];

export function sampleById(id) {
  const sample = SAMPLES.find((s) => s.id === id);
  if (!sample) throw new Error("unknown sample: " + id);
  return sample;
}
